# Generated by Django 4.0.1 on 2022-01-13 04:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('business_model', models.TextField()),
                ('hr_partner', models.TextField()),
                ('finance', models.TextField()),
                ('technology', models.TextField()),
                ('partner_user_ecosystem', models.TextField()),
                ('community', models.TextField()),
                ('roadmap', models.TextField()),
                ('competitor', models.TextField()),
                ('marketcap', models.TextField()),
                ('tokenomics', models.TextField()),
                ('fomo', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(max_length=255, to='topics.Keyword')),
            ],
        ),
    ]
